### ISSUE TITLE
Not able to install from source on mac.

### ISSUE THREAD

**Issue by adarshchbs** [atom-moyer/getpy#4]
running install
running bdist_egg
running egg_info
writing getpy.egg-info/PKG-INFO
writing dependency_links to getpy.egg-info/dependency_links.txt
writing requirements to getpy.egg-info/requires.txt
writing top-level names to getpy.egg-info/top_level.txt
reading manifest file 'getpy.egg-info/SOURCES.txt'
writing manifest file 'getpy.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.9-x86_64/egg
running install_lib
running build_py
running build_ext
building '_getpy' extension
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/adarsh.gupta3/anaconda3/include -arch x86_64 -I/Users/adarsh.gupta3/anaconda3/include -arch x86_64 -DDOCTEST_CONFIG_DISABLE -Ilib/parallel-hashmap -Ilib/pybind11/include -I/Users/adarsh.gupta3/anaconda3/include/python3.8 -c src/getpy.cpp -o build/temp.macosx-10.9-x86_64-3.8/src/getpy.o -w -std=c++17 -stdlib=libc++
src/getpy.cpp:1:10: fatal error: 'pybind11/pybind11.h' file not found
#include <pybind11/pybind11.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
error: command 'gcc' failed with exit status 1

**Comment by atom-moyer** [comment]
I think you did not pull the submodules.

git submodule update --init --recursive

That command should pull the submodules.

**Comment by adarshchbs** [comment]
Thanks for such a quick reply. pulling the submodules solved the above problem but I got a new problem.
I am trying to build it in an conda environment. I tried with python 3.9.1 and python 3.8.5.

running install
running bdist_egg
running egg_info
writing getpy.egg-info/PKG-INFO
writing dependency_links to getpy.egg-info/dependency_links.txt
writing requirements to getpy.egg-info/requires.txt
writing top-level names to getpy.egg-info/top_level.txt
reading manifest file 'getpy.egg-info/SOURCES.txt'
writing manifest file 'getpy.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.9-x86_64/egg
running install_lib
running build_py
running build_ext
building '_getpy' extension
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/adarsh.gupta3/anaconda3/envs/annual_reports/include -arch x86_64 -I/Users/adarsh.gupta3/anaconda3/envs/annual_reports/include -arch x86_64 -DDOCTEST_CONFIG_DISABLE -Ilib/parallel-hashmap -Ilib/pybind11/include -I/Users/adarsh.gupta3/anaconda3/envs/annual_reports/include/python3.7m -c src/getpy.cpp -o build/temp.macosx-10.9-x86_64-3.7/src/getpy.o -w -std=c++17 -stdlib=libc++
In file included from src/getpy.cpp:1:
In file included from lib/pybind11/include/pybind11/pybind11.h:44:
In file included from lib/pybind11/include/pybind11/attr.h:13:
lib/pybind11/include/pybind11/cast.h:579:34: error: aligned allocation function of type 'void *(std::size_t, std::align_val_t)' is only available on macOS 10.14 or newer
                        vptr = ::operator new(type->type_size,
                                 ^
lib/pybind11/include/pybind11/cast.h:579:34: note: if you supply your own aligned allocation functions, use -faligned-allocation to silence this diagnostic
In file included from src/getpy.cpp:1:
lib/pybind11/include/pybind11/pybind11.h:1000:11: error: 'operator delete' is unavailable: introduced in macOS 10.12
        ::operator delete(p, s, std::align_val_t(a));
          ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/new:208:74: note: 'operator delete' has been explicitly marked unavailable here
_LIBCPP_OVERRIDABLE_FUNC_VIS _LIBCPP_AVAILABILITY_SIZED_NEW_DELETE void  operator delete(void* __p, std::size_t __sz, std::align_val_t) _NOEXCEPT;
                                                                         ^
In file included from src/getpy.cpp:1:
lib/pybind11/include/pybind11/pybind11.h:1002:11: error: 'operator delete' is unavailable: introduced in macOS 10.12
        ::operator delete(p, s);
          ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/new:191:74: note: 'operator delete' has been explicitly marked unavailable here
_LIBCPP_OVERRIDABLE_FUNC_VIS _LIBCPP_AVAILABILITY_SIZED_NEW_DELETE void  operator delete(void* __p, std::size_t __sz) _NOEXCEPT;
                                                                         ^
3 errors generated.
error: command 'gcc' failed with exit status 1

**Comment by atom-moyer** [comment]
I think your gcc is out of date. I am not familiar with super familiar with compiling on macOS. I think you need to install developer tools to get all of the new compilers.
